name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]  # when pushed to main branch
  workflow_dispatch:    # can be run manually from GitHub Actions page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2 
        with:
          version: 7
      - run: pnpm install
      - run: pnpm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist